### PR TITLE
Enable qsrv and pvxs to create PVA PVs

### PR DESCRIPTION
**Pull request by GDYendell**

### CODE REVIEW

**Comment by GDYendell** [comment]
Would it be possible to instantiate an instance of the template to make sure it works, like the python copier template does? It would be good to check that install scripts I have added calls for exist in ibek-support.

**Comment by gilesknap** [comment]
> Would it be possible to instantiate an instance of the template to make sure it works, like the python copier template does? It would be good to check that install scripts I have added calls for exist in ibek-support.

Yes we should do this. I just have not got around to it.

**Comment by gilesknap** [comment]
@GDYendell I have one question on these PRs.

Will qserv ever be installed separately to pvxs? It's just making the Dockerfile longer and it feels odd that the qserv install.sh takes no version number. 

The alternative is to just add the lib and dbd in the pvxs install.sh - and it can be done without adding any extra lines to that file. Less is more, right?

Other than that we are all good.

**Comment by GDYendell** [comment]
Sorry I commented [here](https://github.com/epics-containers/ibek-support/pull/51#issuecomment-2237013675).

> I split these into two install scripts as you could possibly want qsrv to make PVA PVs for all your records, but not pvxs to create PVA PVs from the info tags.

I think it makes sense to split them but don't feel strongly about it. Any thoughts @coretl ?

**Comment by coretl** [comment]
`qsrv.dbd` is the old one, `pvxsIoc.dbd` completely replaces it (including making PVA PVs from info tags), so we never need `qsrv.dbd`. I suggest you get rid of the `qsrv/install.sh` here and in ibek-support

**Comment by GDYendell** [comment]
Updated to only use pvxs and it still works the same.

**Pull request merged**
